Query:
  ProVotes:
    host: localhost
    port: 3306
    database: root
    username: root
    password: password
    query: 'SELECT TotalVotes FROM ProVotes WHERE UUID = {uuid}'
  PlayerPoints:
    host: localhost
    port: 3306
    database: root
    username: root
    password: password
    query: 'SELECT points FROM playerpoints WHERE playername = {uuid}'